version: "3.7"
services:
  app:
    image: docker.pkg.github.com/yanislav-igonin/haiku-bot/haiku-bot:latest
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - WEBHOOK_ENABLED=false
    restart: unless-stopped
