name: Push

on: push

jobs:
  # lint:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Use Node.js 14
  #       uses: actions/setup-node@v2-beta
  #       with:
  #         node-version: 14.x
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Lint
  #       run: npm run lint

  build:
    # needs: lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build

  release:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Build docker image and push to GitHub registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: yanislav-igonin/haiku-bot/haiku-bot
          dockerfile: Dockerfile
          tags: latest
